- name: Install Apache2. This is my 1st task in 1st play
  apt:
    name: apache2
    state: latest

- name: Install httpd. Some random task
  yum:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start apache2. This is my 2nd task in 1st play
  service:
    name: apache2
    state: started

- name: Create sample folder(directory). This is my 3rd task in 1st play
  file:
    path: /home/azureuser/sample
    state: directory

- name: Copy one.txt to sample dir in remote location
  copy:
    src: /home/azureuser/one.txt
    dest: /home/azureuser/sample/one.txt

- name: Copy abc.html to /var/www/html/abc.html.
  template:
    src: /home/azureuser/abc.html.j2
    dest: /var/www/html/abc.html

- name: Copy conf file to some location
  copy:
    src: /home/azureuser/dummyconf.txt
    dest: /home/azureuser/dummyconf.txt
  notify:
    - Restart apache2
